name: Build & Deploy to Github Pages

on:
  push:
    branches: [main]

jobs:
  node-to-gh:
    runs-on: ubuntu-latest
    name: Build & Deploy to Github Pages
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: echo 'colmlang.com' >> ./out/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
